# RAG master runner (refactored)

Runs config first, then each logical section.

In [11]:
%run -i "00_config.ipynb"

Project root: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop
CFG_NAME: chunk_w512_ov0.25
PASSAGES_PATH: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\data\processed\passages.parquet
Q_PATH: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\data\processed\questions_eval.parquet
EMB_DIR: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\embeddings\intfloat_e5-small-v2\chunk_w512_ov0.25
RESULTS_DIR: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\results

In [4]:
%run -i "01_data_load_prep.ipynb"

Resolving data files:   0%|          | 0/26 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/26 [00:00<?, ?it/s]

Loaded rows: 500
Index(['question', 'question_id', 'question_source', 'entity_pages',
       'search_results', 'answer'],
      dtype='object')
  question_id                                                  question_clean  \
0   dpql_3252  Which island in Kent is the second largest of England's isles?

                                                         answer_text
0  Isle of Sheppey , Isle of Sheppy , Shurland Hall , Shurland House
Context column: 'ctx' | non-empty rows: 449 / 500
After removing empty context rows: 449 rows remain.

In [5]:
%run -i "02_chunking.ipynb"

Duplicate passage_id count: 0
Saved 10,938 passages to 'C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\data\processed\passages.parquet'. (chunk_size=512, overlap_ratio=0.25)
Docs: 449 | Avg chunks/doc: 24.36

In [8]:
%run -i "03_embeddings.ipynb"

Saved canonical passages: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\embeddings\intfloat_e5-small-v2\chunk_w512_ov0.25\passages_canonical.parquet
Saved id_map: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\embeddings\intfloat_e5-small-v2\chunk_w512_ov0.25\id_map.csv
Embeddings already exist — skipping embedding step.
Embeddings: (10938, 384) saved → C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\embeddings\intfloat_e5-small-v2\chunk_w512_ov0.25\emb.npy
IDs saved → C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\embeddings\intfloat_e5-small-v2\chunk_w512_ov0.25\ids.npy
Meta saved → C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\embeddings\intfloat_e5-small-v2\chunk_w512_ov0.25\meta.json
Time: skipped

In [9]:
%run -i "04_faiss_index.ipynb"

[OK] HNSW index saved → C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\indexes\intfloat_e5-small-v2\chunk_w512_ov0.25\hnsw_M32_efC200_efS64\index.faiss
     Vectors: 10938 | Dim: 384 | Metric: IP(cosine)
     HNSW(M=32, efC=200, efS=64)
     Build time: 1.60s | Peak RSS: 1513.1 MB | File: 18.9 MB
     Meta: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\indexes\intfloat_e5-small-v2\chunk_w512_ov0.25\hnsw_M32_efC200_efS64\meta.json

In [12]:
%run -i "05_retrieval_and_llm_setup.ipynb"

Loaded canonical passages: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\embeddings\intfloat_e5-small-v2\chunk_w512_ov0.25\passages_canonical.parquet
Rows: 10938
Loaded passages: 10938
Loaded id_map: 10938
Index path: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\indexes\intfloat_e5-small-v2\chunk_w512_ov0.25\hnsw_M32_efC200_efS64\index.faiss
efsearch =  None
=== BM25 retriever metrics ===

,Recall@5,MRR@5,mean_retrieval_latency_ms@5,mean_mem_peak_mb@5,Recall@10,MRR@10,mean_retrieval_latency_ms@10,mean_mem_peak_mb@10,Recall@50,MRR@50,mean_retrieval_latency_ms@50,mean_mem_peak_mb@50
0,0.842105,0.749089,25.510634,4.249813,0.862348,0.751838,25.510634,4.249813,0.917004,0.754672,25.510634,4.249813

efsearch =  96
=== Dense retriever metrics ===

,Recall@5,MRR@5,mean_retrieval_latency_ms@5,mean_mem_peak_mb@5,Recall@10,MRR@10,mean_retrieval_latency_ms@10,mean_mem_peak_mb@10,Recall@50,MRR@50,mean_retrieval_latency_ms@50,mean_mem_peak_mb@50
0,0.746964,0.612078,168.702903,1.782703,0.805668,0.620303,168.702903,1.782703,0.88664,0.6251,168.702903,1.782703

efsearch =  96
=== Hybrid retriever metrics ===

,Recall@5,MRR@5,mean_retrieval_latency_ms@5,mean_mem_peak_mb@5,Recall@10,MRR@10,mean_retrieval_latency_ms@10,mean_mem_peak_mb@10,Recall@50,MRR@50,mean_retrieval_latency_ms@50,mean_mem_peak_mb@50
0,0.787449,0.656545,220.743452,1.825229,0.850202,0.665704,220.743452,1.825229,0.906883,0.669081,220.743452,1.825229

Total evaluation questions: 494

llama_context: n_ctx_per_seq (2048) < n_ctx_train (32768) -- the full capacity of the model will not be utilized

Loaded LLama model from: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\models\Qwen2.5-7B-Instruct-Q4_K_M.gguf

In [13]:
%run -i "06_rag_runs.ipynb"

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

Saved RAG outputs to: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\results\rag_answers_dense.parquet
Saved RAG outputs to: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\results\rag_answers_bm25.parquet
Saved RAG outputs to: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\results\rag_answers_hybrid.parquet

In [14]:
%run -i "07_evaluation_and_analysis.ipynb"

Loaded: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\results\rag_answers_bm25.parquet
Loaded: C:\Users\Harman\Documents\GISMA\Term_4\Thesis_Redo\Thesis_Implementation\rag_env\Project\rag-laptop\results\rag_answers_dense.parquet
BM25 Results are as follows:
Number of evaluated questions: 50
Exact Match (EM):                 0.4000
F1:                               0.4987
Number of evaluated questions: 50
Exact Match (EM):                 0.3600
F1:                               0.4460
Number of evaluated questions: 50
Exact Match (EM):                 0.3000
F1:                               0.4010